### ISSUE TITLE
Sprouts wallet not able to sync with blockchain

### ISSUE THREAD

**Issue by sauhaard** [gjhiggins/sprouts#1]
I transferred sprouts from coinexchange account to sprouts wallet by github. The wallet shows zero balance and shows that its downloading the blocks but is not able to do it. It stays on 0% in downloading blocks. I have also checked on sprouts blockchain that the transaction is successfully done. Please help me with this issue. I also noticed that it doesn't start the sync process until I connect through a vpn.

**Comment by gjhiggins** [comment]
Have you followed the advice given on the bitcointalk thread?
https://bitcointalk.org/index.php?topic=1798901.msg20983628#msg20983628

**Comment by sauhaard** [comment]
Thanks a lot. It worked like a charm!
